version: '3'
services:
  runner:
    build:
          context: .
          dockerfile: Dockerfile
    ports:
      - '5003:5000'
    volumes:
      - "./result:/root/results"
      - "./carsonella_ruddii:/root/carsonella"
